### ISSUE TITLE
DraggableSheet moves up when keyboard opens

### ISSUE THREAD

**Issue by faizanje** [fujidaiti/smooth_sheets#184] opened 2024-06-27 23:26 UTC
I am experiencing an issue with the DraggableSheet. Whenever the keyboard opens, the DraggableSheet always moves up, regardless of the current state or configuration. This behavior is undesirable and disrupts the user experience.

**Steps to reproduce:**

1.  Add the above code in your Flutter project.
2.  Run the project.
3.  Tap on the TextField to open the keyboard.
4.  Observe that the DraggableSheet moves up.

`import 'package:flutter/material.dart';  
import 'package:smooth_sheets/smooth_sheets.dart';

**Expected behavior:**  
The DraggableSheet should stay in its current position when the keyboard opens.

**Actual behavior:**  
The DraggableSheet moves up when the keyboard opens.

```
import 'package:flutter/material.dart';  
import 'package:smooth_sheets/smooth_sheets.dart';  
  
void main() {  
  runApp(const MyApp());  
}  
  
class MyApp extends StatelessWidget {  
  const MyApp({super.key});  
  
  @override  
  Widget build(BuildContext context) {  
    return const MaterialApp(  
      home: Scaffold(  
        resizeToAvoidBottomInset: false,  
  body: SmoothSheetDemo(),  
  ),  
  );  
  }  
}  
  
class SmoothSheetDemo extends StatefulWidget {  
  const SmoothSheetDemo({super.key});  
  
  @override  
  _SmoothSheetDemoState createState() => _SmoothSheetDemoState();  
}  
  
class _SmoothSheetDemoState extends State<SmoothSheetDemo> {  
  final SheetController _smoothSheetController = SheetController();  
  
  @override  
  Widget build(BuildContext context) {  
    final List<double> snaps = [0.3, 0.5, 1.0];  
  const minExtent = Extent.proportional(0.3);  
  final extentSnaps = snaps.map((e) => Extent.proportional(e)).toList();  
  final physics = SnappingSheetPhysics(  
      snappingBehavior: SnapToNearest(  
        snapTo: extentSnaps,  
  ),  
  );  
  
  return SafeArea(  
      child: Stack(  
        children: [  
          const Placeholder(),  
  DraggableSheet(  
            minExtent: minExtent,  
  controller: _smoothSheetController,  
  initialExtent: minExtent,  
  physics: physics,  
  child: buildContent(),  
  ),  
  ],  
  ),  
  );  
  }  
  
 Widget buildContent() {  
  return Container(  
    color: Colors.grey[900],  
  child: Column(  
      children: [  
        const SizedBox(height: 16),  
  const TextField(),  
  const SizedBox(height: 16),  
  Expanded(  
          child: ListView(  
            children: List.generate(  
              100,  
  (index) => Container(  
                margin: const EdgeInsets.all(4),  
  child: const FlutterLogo(),  
  ),  
  ),  
  ),  
  ),  
  ],  
  ),  
  );  
} 
}
```
[Screen_recording_20240628_043148.webm](https://github.com/fujidaiti/smooth_sheets/assets/50191165/4414c8be-b6fc-42b0-b7df-d74d6e9bff0e)

**Comment by fujidaiti** [comment] 2024-06-28 01:27
Hi @faizanje, 

>Whenever the keyboard opens, the DraggableSheet always moves up, 

This is the intended behavior of the sheet. If you want to keep the current sheet position even when the keyboard opens, wrap your content in a `SheetContentScaffold`:

```dart
          DraggableSheet(
            minExtent: minExtent,
            controller: _smoothSheetController,
            initialExtent: minExtent,
            physics: physics,
            child: SheetContentScaffold(
              body: buildContent(),
            ),
          ),
```

Moreover, nesting a sheet in a `Scaffold` should be avoided especially when the sheet has textboxes. Please see [this comment](https://github.com/fujidaiti/smooth_sheets/discussions/66#discussioncomment-8809502) for more details.

**Comment by faizanje** [comment] 2024-06-28 10:22
Thank you for your quick response. Wrapping my content in a `SheetContentScaffold `has resolved the issue.

**Comment by faizanje** [comment] 2024-06-28 17:17
Thank you for your response and the suggestion to use `SheetContentScaffold`. However, the issue still persists, the sheet still partially moves up when the keyboard opens. I also noted your comment about avoiding nesting a sheet within a Scaffold, so I removed the scaffold from the root.

**Here is the updated code I used:**
```
import 'package:flutter/material.dart';
import 'package:smooth_sheets/smooth_sheets.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: SmoothSheetDemo(),
    );
  }
}

class SmoothSheetDemo extends StatefulWidget {
  const SmoothSheetDemo({super.key});

  @override
  _SmoothSheetDemoState createState() => _SmoothSheetDemoState();
}

class _SmoothSheetDemoState extends State<SmoothSheetDemo> {
  final SheetController _smoothSheetController = SheetController();

  @override
  Widget build(BuildContext context) {
    final List<double> snaps = [0.3, 0.5, 1.0];
    const minExtent = Extent.proportional(0.3);
    final extentSnaps = snaps.map((e) => Extent.proportional(e)).toList();
    final physics = SnappingSheetPhysics(
      snappingBehavior: SnapToNearest(
        snapTo: extentSnaps,
      ),
    );

    return SafeArea(
      child: Stack(
        children: [
          const Scaffold(
            body: Column(
              children: [
                TextField(),
                Expanded(
                  child: Placeholder(),
                )
              ],
            ),
            resizeToAvoidBottomInset: false,
          ),
          DraggableSheet(
            minExtent: minExtent,
            controller: _smoothSheetController,
            initialExtent: minExtent,
            physics: physics,
            child: SheetContentScaffold(
              body: buildContent(),
            ),
          ),
        ],
      ),
    );
  }

  Widget buildContent() {
    return Container(
      color: Colors.grey[900],
      child: Column(
        children: [
          const SizedBox(height: 16),
          const TextField(),
          const SizedBox(height: 16),
          Expanded(
            child: ListView(
              children: List.generate(
                100,
                (index) => Container(
                  margin: const EdgeInsets.all(4),
                  child: const FlutterLogo(),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

**Comment by faizanje** [comment] 2024-06-28 17:20
[Screen_recording_20240628_221948.webm](https://github.com/fujidaiti/smooth_sheets/assets/50191165/8fd8407a-8429-4f92-aa76-80566539462a)

**Comment by faizanje** [comment] 2024-06-28 22:54
@fujidaiti Any update on this?

**Comment by fujidaiti** [comment] 2024-06-29 04:05
I'll close this as a duplicate of #14. Opening the keyboard on a non-fullscreen sheet is currently unstable. Please follow #14 for further updates.

**Closed by fujidaiti** 2024-06-29 04:05 UTC
Labels: duplicate

**Comment by fujidaiti** [comment] 2024-07-11 02:11
I noticed that [a fix for #14](https://github.com/fujidaiti/smooth_sheets/pull/189) didn't solve the issue mentioned in [this comment](https://github.com/fujidaiti/smooth_sheets/issues/184#issuecomment-2197356152). I have created a new issue to track this bug instead of reopening this issue (#192), so please follow up on that.

**Comment by dickermoshe** [comment] 2024-09-13 00:06
Quick & Dirty workaround:
```
Stack(children: [
  Scaffold(...)
  MediaQuery.removeViewInsets(
    removeBottom: true,
    context: context,
    child: ScrollableSheet(...)))
```

**Comment by Jack74r** [comment] 2025-03-16 09:51
Hi
I think i have same issue, i try to make UI like google map, draggable bottom sheet, and search field on the top.
But the bottom sheet should (in this case) dont change the state or move up the keyboard.

On the example of airbnb on last commit (5fad0b8bab04fe88cc08d5c43e9d7edd1efa95be) , i just added textfield to show the problem.

How it's possible to fix this pleas

https://github.com/user-attachments/assets/20787d40-1056-4c50-b4c8-39bfd5c61642

Thank you

**Comment by fujidaiti** [comment] 2025-03-20 02:42
@Jack74r Setting Scaffold. resizeToAvoidBottomInset to false is the most easiest way to work around this unless you don't put a text field within the sheet
